### ISSUE TITLE
Remove/Reduce docker output

### ISSUE THREAD

**Issue by staabm** [OskarStark/php-cs-fixer-ga#1]
The github action status tab should not be polluted with docker information, but just show the actual php-cs-fixer output

**Comment by OskarStark** [comment]
You are right, but I don’t find any solution yet as github pulls their action runner which then pulls my image 🤔

**Comment by OskarStark** [comment]
This should be fixed by the new Workflow CI/CD Pipeline:
<img width="1669" alt="Screenshot 2019-08-14 09 21 14" src="https://user-images.githubusercontent.com/995707/63001910-f35db800-be74-11e9-96d8-8817b5cfce12.png">
