### ISSUE TITLE
Integration with Prettier

### ISSUE THREAD

**Issue by AustinW** [OskarStark/php-cs-fixer-ga#19]
My .php_cs includes an integration with prettier/plugin-php. When I run the action, I get `sh: yarn: command not found`. I tried adding yarn myself, but it doesn't seem to exist in the environment when php-cs-fixer is running. Here is an example of the script:

https://gist.github.com/Billz95/9d5fad3af728b88540fa831b73261733?spm=a2c6h.14275010.0.0.6a8669d3D5xKYR#file-prettierphpfixer-php-L65

Any suggestions to get it to recognize yarn? Thanks.

**Comment by OskarStark** [comment]
Unfortunately yarn is not included in this action 👎🏻

**Comment by OskarStark** [comment]
I am also not a big fan of fixing JS files using a PHP fixer 🙁
