### ISSUE TITLE
`GITHUB_TOKEN` not used?

### ISSUE THREAD

**Issue by michaelw90** [OskarStark/php-cs-fixer-ga#2]
Taking a look through the code I can't see any usage of the `GITHUB_TOKEN` secret? If it's not needed, I'm more than happy to raise a PR to remove it from the example workflow etc.

Is it necessary?

**Comment by OskarStark** [comment]
It was my first attempt and I think you are right that it is not necessary.

Would be happy to receive a PR 👌🏻

**Comment by michaelw90** [comment]
No worries, everyone starts somewhere ... :) I recently built my first PHP one, and was slightly confused when reviewing yours. 

PR raised! 👍
