### ISSUE TITLE
Failure with 2.18.6

### ISSUE THREAD

**Issue by emodric** [OskarStark/php-cs-fixer-ga#35]
Hi,

Using the new 2.18.6 version of the action fails with the following log:

```
Pull down action image 'oskarstark/php-cs-fixer-ga:2.18.6'
  /usr/bin/docker pull oskarstark/php-cs-fixer-ga:2.18.6
  Error response from daemon: manifest for oskarstark/php-cs-fixer-ga:2.18.6 not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 6.792 seconds before retry.
  /usr/bin/docker pull oskarstark/php-cs-fixer-ga:2.18.6
  Error response from daemon: manifest for oskarstark/php-cs-fixer-ga:2.18.6 not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 6.632 seconds before retry.
  /usr/bin/docker pull oskarstark/php-cs-fixer-ga:2.18.6
  Error response from daemon: manifest for oskarstark/php-cs-fixer-ga:2.18.6 not found: manifest unknown: manifest unknown
Error: Docker pull failed with exit code 1
```

I suppose this is due to tag for the repo and Docker image missing.

**Comment by OskarStark** [comment]
Hmm, looks like the tag was not created on Github and then no Docker image was tagged.

Give it a try in 30 minutes, if the tag is available at docker hub, please close this issue, thanks

**Comment by emodric** [comment]
Will do :+1:

**Comment by emodric** [comment]
Everything is well now, closing!

Thanks @OskarStark !

**Comment by emodric** [comment]
Hi, it seems this happened again with 3.0.2 tag. It is happening since yesterday.

I've tried waiting a bit as you instructed before, but one day later, it still does not work.

**Comment by OskarStark** [comment]
3.0.2 was tagged today, before the tag was not created on docker hub

**Comment by emodric** [comment]
Says here 3.0.2 was created 3 days ago? :) But even if that info is wrong, my project definitely somehow did try to use 3.0.2 yesterday. :)

![image](https://user-images.githubusercontent.com/362286/130067940-85be231a-701e-4988-a0c9-8f8b936fa5f6.png)

**Comment by OskarStark** [comment]
Yes it was created, but not build on docker hub.
I deleted the release and created it again to be build automatically.

Should work now as far as I can see

**Comment by emodric** [comment]
Thanks!

Does this happen due to some hiccup in GH -> Docker communication?
