### ISSUE TITLE
Look just on the pushed files

### ISSUE THREAD

**Issue by Pyrovatis** [OskarStark/php-cs-fixer-ga#38]
This is great tool because i can use php-cs-fixer without installing it on the project!  :)
But i have one question, is it possible to check by gha just a files that was just pushed? I try to append this to my project, but as i see it checks EVERY file on the project, but i want to fix only "new", just pushed files.

Thanks in advance for answer!

**Comment by OskarStark** [comment]
AFAIK this is not supported out of the box for cs fixer.

Why don't you execute it on the main branch once so that everything is fixed and then against every PR?

**Comment by Pyrovatis** [comment]
Yes, I did it on this way :)

And thanks for this project, it's really helpfull since FriendsofPhp doesn't make their own gha to use php-cs-fixer.

**Comment by OskarStark** [comment]
Welcome 😎
