### ISSUE TITLE
Not working on ubuntu-22.04

### ISSUE THREAD

**Issue by garak** [OskarStark/php-cs-fixer-ga#53]
I tried to use the newer Ubuntu version, and I got the following errors:

>Pull down action image 'oskarstark/phpstan-ga'
  /usr/bin/docker pull oskarstark/phpstan-ga
  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  Using default tag: latest
  Warning: Docker pull failed with exit code 1, back off 7.814 seconds before retry.
  /usr/bin/docker pull oskarstark/phpstan-ga
  Using default tag: latest
  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  Warning: Docker pull failed with exit code 1, back off 3.291 seconds before retry.
  /usr/bin/docker pull oskarstark/phpstan-ga
  Using default tag: latest
  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error: Docker pull failed with exit code 1

**Comment by OskarStark** [comment]
Hmm strange, it looks more like a docker issue and not of the image itself

**Comment by garak** [comment]
> Hmm strange, it looks more like a docker issue and not of the image itself

I was thinking the same. Do you have an idea to point me to the correct project to open an issue?

**Comment by garak** [comment]
I tried again after a while and it's working now.

**Comment by OskarStark** [comment]
Thanks for coming back
