### ISSUE TITLE
3.9.0 released

### ISSUE THREAD

**Issue by armetiz** [OskarStark/php-cs-fixer-ga#54]
Hi there.

PHP-CS-Fixer has been bumped to [3.9.0](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/CHANGELOG.md#changelog-for-v390).

Regards,

Thomas.

**Comment by armetiz** [comment]
@OskarStark did you saw notification?

Regards

**Comment by OskarStark** [comment]
Already done
