### ISSUE TITLE
Please add tag for v3.22.0

### ISSUE THREAD

**Issue by mortenscheel** [OskarStark/php-cs-fixer-ga#85]
The latest is currently v3.20.0 so it's a couple of versions behind.
v3.22.0 has added some new fixers and deprecated old ones. But if you replace the deprecated fixers, the run fails on Github Actions which runs 3.20.0

**Comment by mortenscheel** [comment]
As a side note, I think the process can be automated by using `workflow_dispatch`: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

**Comment by OskarStark** [comment]
Open for a PR which automates this.

Please create PRs for the new versions, so I can merge them one after another an create a release. Thanks
