### ISSUE TITLE
Build images for other architectures

### ISSUE THREAD

**Issue by relthyg** [OskarStark/php-cs-fixer-ga#96]
Currently, only the image for amd64 is built, which leaves Apple's new M1/M2 chips (arm64) out. An example of how this can be achieved can be found [here](https://github.com/apache/tika-docker/pull/19/files#diff-a894120de2d841cb7e1e40a5faee2225d8810cc3fe03ecd231b07322594fca1c). As far as I can see, it would be necessary

- to install Qemu in addition to BuildX
- define a list of desired architectures
- to build these architectures

Do you think this would be possible?

**Comment by OskarStark** [comment]
I think it would, open for a PR?

**Comment by shyim** [comment]
It seems like the arm64 build is gone from Docker Hub

**Comment by OskarStark** [comment]
I switched from docker hub builds to building via GitHub Actions. PR welcome 👍🏻
